export const products = [
  {
    fieldData: {
      ProductName: "Appointed Workbook",
      ProductType__c: "Hardgoods",
      Season: "",
      __kp_Product_ID: 10597,
      flag_topTen: 1,
    },
    modId: "8",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 24.0,
          "prod_VARIANT::QtyOnHand": 9,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7571",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Books & Stationary",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "110",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2296",
  },
  {
    fieldData: {
      ProductName: "Arcadia Orange Cookie - Ruze Cake House",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10598,
      flag_topTen: "",
    },
    modId: "9",
    portalData: {
      prod_VARIANT: [
        {
          modId: "10",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 12,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7572",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 4,
        returnedCount: 4,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2297",
  },
  {
    fieldData: {
      ProductName: "Arcadia Orange Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10599,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "138",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Mason Jar",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 85.0,
          "prod_VARIANT::QtyOnHand": 141,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7573",
        },
        {
          modId: "13",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Small Centerpiece",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 135.0,
          "prod_VARIANT::QtyOnHand": 13,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7574",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2298",
  },
  {
    fieldData: {
      ProductName: "Biltmore Bloom",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10600,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "17",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 210.0,
          "prod_VARIANT::QtyOnHand": 18,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7575",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2299",
  },
  {
    fieldData: {
      ProductName: "Bright Love Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10601,
      flag_topTen: 1,
    },
    modId: "6",
    portalData: {
      prod_VARIANT: [
        {
          modId: "88",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 85.0,
          "prod_VARIANT::QtyOnHand": 87,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7576",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2300",
  },
  {
    fieldData: {
      ProductName: "Camelback Flowershop Signature Candle Collection",
      ProductType__c: "Hardgoods",
      Season: "",
      __kp_Product_ID: 10602,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Flowershop",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 38.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7577",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Arcadia Orange",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 38.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7578",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Phoenix Date",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 38.0,
          "prod_VARIANT::QtyOnHand": 10,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7579",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Home Fragrance",
          "prod_colljoin_COLL::Count": 35,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "108",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Home & Objects",
          "prod_colljoin_COLL::Count": 49,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "109",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2301",
  },
  {
    fieldData: {
      ProductName: "CF Classic Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10603,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Mason jar",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 75.0,
          "prod_VARIANT::QtyOnHand": -2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7580",
        },
        {
          modId: "15",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Small Centerpiece",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 125.0,
          "prod_VARIANT::QtyOnHand": 14,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7581",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2302",
  },
  {
    fieldData: {
      ProductName: "Chubby Bud Vase",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10604,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "3",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "pinks",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 3,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7582",
        },
        {
          modId: "5",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "wild flowers",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 9,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7583",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "whites",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 5,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7584",
        },
        {
          modId: "3",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Roses",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 55.0,
          "prod_VARIANT::QtyOnHand": 3,
          "prod_VARIANT::SortOrder": 4,
          "prod_VARIANT::Unit": "",
          recordId: "7585",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Greens",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 6,
          "prod_VARIANT::SortOrder": 5,
          "prod_VARIANT::Unit": "",
          recordId: "7586",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Peonies (out of season)",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 55.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 6,
          "prod_VARIANT::Unit": "",
          recordId: "7587",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 6,
        returnedCount: 6,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2303",
  },
  {
    fieldData: {
      ProductName: "Compartes Salted Pistachio Dark Chocolate Bar",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10605,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 10.0,
          "prod_VARIANT::QtyOnHand": 40,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7588",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2304",
  },
  {
    fieldData: {
      ProductName: "Dafna",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10606,
      flag_topTen: "",
    },
    modId: "2",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 325.0,
          "prod_VARIANT::QtyOnHand": 10,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7589",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2305",
  },
  {
    fieldData: {
      ProductName: "Daisy Cookie - Ruze Cake House",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10607,
      flag_topTen: 1,
    },
    modId: "7",
    portalData: {
      prod_VARIANT: [
        {
          modId: "4",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 7,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7590",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2306",
  },
  {
    fieldData: {
      ProductName: "Daisy Sugar Cookie",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10608,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "5",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 6,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7591",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2307",
  },
  {
    fieldData: {
      ProductName: "Designer's Choice Everyday Wraps",
      ProductType__c: "Wraps",
      Season: "",
      __kp_Product_ID: 10609,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Regular",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 65.0,
          "prod_VARIANT::QtyOnHand": -2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7592",
        },
        {
          modId: "33",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Medium",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 85.0,
          "prod_VARIANT::QtyOnHand": 32,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7593",
        },
        {
          modId: "9",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Large",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 125.0,
          "prod_VARIANT::QtyOnHand": 8,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7594",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2308",
  },
  {
    fieldData: {
      ProductName: "Gingham Greens",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10610,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "3",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 75.0,
          "prod_VARIANT::QtyOnHand": 3,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7595",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2309",
  },
  {
    fieldData: {
      ProductName: "Gray Gardens Orchid",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10611,
      flag_topTen: "",
    },
    modId: "7",
    portalData: {
      prod_VARIANT: [
        {
          modId: "24",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 250.0,
          "prod_VARIANT::QtyOnHand": 25,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7596",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Plant Collection",
          "prod_colljoin_COLL::Count": 19,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "102",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Orchids",
          "prod_colljoin_COLL::Count": 15,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "103",
        },
        {
          modId: "5",
          "prod_colljoin_COLL::Collection": "Winter Collection 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "112",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 5,
        returnedCount: 5,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2310",
  },
  {
    fieldData: {
      ProductName: "Great Basin",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10612,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "9",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Small",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 165.0,
          "prod_VARIANT::QtyOnHand": 9,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7597",
        },
        {
          modId: "13",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Medium",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 285.0,
          "prod_VARIANT::QtyOnHand": 13,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7598",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Large",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 450.0,
          "prod_VARIANT::QtyOnHand": 3,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7599",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Plant Collection",
          "prod_colljoin_COLL::Count": 19,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "102",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2311",
  },
  {
    fieldData: {
      ProductName: "In the Buff",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10613,
      flag_topTen: 1,
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 245.0,
          "prod_VARIANT::QtyOnHand": 29,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7600",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2312",
  },
  {
    fieldData: {
      ProductName: "Jacob Sensii",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10614,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Small",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 40.0,
          "prod_VARIANT::QtyOnHand": 10,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7601",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Medium",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 75.0,
          "prod_VARIANT::QtyOnHand": 9,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7602",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2313",
  },
  {
    fieldData: {
      ProductName: "Joshua Tree First Press Coffee",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10615,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 20.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7603",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2314",
  },
  {
    fieldData: {
      ProductName: "La Petite Pink Tulipe",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10616,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 145.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7604",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Romance",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "93",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2315",
  },
  {
    fieldData: {
      ProductName: "Lieu Dit Rose",
      ProductType__c: "Wine",
      Season: "",
      __kp_Product_ID: 10617,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "5",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 25.0,
          "prod_VARIANT::QtyOnHand": 5,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7605",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Wine & Flower Gifts",
          "prod_colljoin_COLL::Count": 42,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "94",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2316",
  },
  {
    fieldData: {
      ProductName: "Maison Louis Marie Candle",
      ProductType__c: "Hardgoods",
      Season: "",
      __kp_Product_ID: 10618,
      flag_topTen: 1,
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.03 L' Etang Noir",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 42.0,
          "prod_VARIANT::QtyOnHand": 10,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7606",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.04 - Bois de Balincourt",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 42.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7607",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.09 - Vallee de Farney",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 42.0,
          "prod_VARIANT::QtyOnHand": 6,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7608",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No. 11 - La Themis Candle",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 42.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 4,
          "prod_VARIANT::Unit": "",
          recordId: "7609",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Home Fragrance",
          "prod_colljoin_COLL::Count": 35,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "108",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Home & Objects",
          "prod_colljoin_COLL::Count": 49,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "109",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 4,
        returnedCount: 4,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2317",
  },
  {
    fieldData: {
      ProductName: "Maison Louis Marie Mini Perfume Oil",
      ProductType__c: "Hardgoods",
      Season: "",
      __kp_Product_ID: 10619,
      flag_topTen: "",
    },
    modId: "2",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.03 - L'Etang Noir",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 18.0,
          "prod_VARIANT::QtyOnHand": 24,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7610",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.04 - Bois de Balincourt",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 18.0,
          "prod_VARIANT::QtyOnHand": 22,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7611",
        },
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "No.09 - Vallee de Farney",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 18.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7612",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2318",
  },
  {
    fieldData: {
      ProductName: "Me Time Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10620,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "69",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 95.0,
          "prod_VARIANT::QtyOnHand": 71,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7613",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2319",
  },
  {
    fieldData: {
      ProductName: "Mirzam Ragas Dark Chocolate w/ Arabic Bread",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10621,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 11.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7614",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2320",
  },
  {
    fieldData: {
      ProductName: "Mirzam White Chocolate w/ Cardamon",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10622,
      flag_topTen: 1,
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 11.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7615",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2321",
  },
  {
    fieldData: {
      ProductName: "Monsoon Matcha",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10623,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Green Label",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 58.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7616",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Red Label",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 58.0,
          "prod_VARIANT::QtyOnHand": 12,
          "prod_VARIANT::SortOrder": 4,
          "prod_VARIANT::Unit": "",
          recordId: "7617",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2322",
  },
  {
    fieldData: {
      ProductName: "Mums Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10624,
      flag_topTen: 1,
    },
    modId: "6",
    portalData: {
      prod_VARIANT: [
        {
          modId: "27",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 85.0,
          "prod_VARIANT::QtyOnHand": 27,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7618",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2323",
  },
  {
    fieldData: {
      ProductName: "Peach Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10625,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "6",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 85.0,
          "prod_VARIANT::QtyOnHand": 6,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7619",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2324",
  },
  {
    fieldData: {
      ProductName: "Peony Chubby Bud",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10626,
      flag_topTen: "",
    },
    modId: "7",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 95.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7620",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Weddings & Events",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "95",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 5,
        returnedCount: 5,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2325",
  },
  {
    fieldData: {
      ProductName: "Peony Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10627,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "3",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 95.0,
          "prod_VARIANT::QtyOnHand": 3,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7621",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2326",
  },
  {
    fieldData: {
      ProductName: "Petite Garden Centerpiece",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10628,
      flag_topTen: 1,
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "6",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Single",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 55.0,
          "prod_VARIANT::QtyOnHand": 11,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7622",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Double",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 100.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7623",
        },
        {
          modId: "3",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Triple",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 150.0,
          "prod_VARIANT::QtyOnHand": 5,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7624",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Weddings & Events",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "95",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2327",
  },
  {
    fieldData: {
      ProductName: "Petite Peach Wrap",
      ProductType__c: "Wraps",
      Season: "",
      __kp_Product_ID: 10629,
      flag_topTen: 1,
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 66,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7625",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2328",
  },
  {
    fieldData: {
      ProductName: "Petite Pink Wrap",
      ProductType__c: "Wraps",
      Season: "",
      __kp_Product_ID: 10630,
      flag_topTen: 1,
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 45.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7626",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2329",
  },
  {
    fieldData: {
      ProductName: "Potted Olive Tree",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10631,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "10",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 125.0,
          "prod_VARIANT::QtyOnHand": 10,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7627",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "5",
          "prod_colljoin_COLL::Collection": "Winter Collection 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "112",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2330",
  },
  {
    fieldData: {
      ProductName: "Rosi Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10632,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "26",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 75.0,
          "prod_VARIANT::QtyOnHand": 30,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7628",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2331",
  },
  {
    fieldData: {
      ProductName: "Ruze Cake House Chocolate Caramel Pretzel Rods",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10633,
      flag_topTen: 1,
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 18.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7629",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2332",
  },
  {
    fieldData: {
      ProductName: "Seasonal Monsoon",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10634,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Small",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 50.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7630",
        },
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Medium",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 95.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7631",
        },
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Large",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 140.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7632",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Plant Collection",
          "prod_colljoin_COLL::Count": 19,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "102",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2333",
  },
  {
    fieldData: {
      ProductName: "Self Care Box",
      ProductType__c: "Gift Boxes",
      Season: "",
      __kp_Product_ID: 10635,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 225.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7633",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2334",
  },
  {
    fieldData: {
      ProductName: "Small Gold Tooth Aloe",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10636,
      flag_topTen: "",
    },
    modId: "2",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 40.0,
          "prod_VARIANT::QtyOnHand": 90,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7634",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2335",
  },
  {
    fieldData: {
      ProductName: "Smoky Orchid Garden",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10637,
      flag_topTen: "",
    },
    modId: "8",
    portalData: {
      prod_VARIANT: [
        {
          modId: "21",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "small (pictured)",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 150.0,
          "prod_VARIANT::QtyOnHand": 21,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7635",
        },
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "medium",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 250.0,
          "prod_VARIANT::QtyOnHand": 0,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7636",
        },
        {
          modId: "1",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "large",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 350.0,
          "prod_VARIANT::QtyOnHand": 1,
          "prod_VARIANT::SortOrder": 3,
          "prod_VARIANT::Unit": "",
          recordId: "7637",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Plant Collection",
          "prod_colljoin_COLL::Count": 19,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "102",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Orchids",
          "prod_colljoin_COLL::Count": 15,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "103",
        },
        {
          modId: "5",
          "prod_colljoin_COLL::Collection": "Winter Collection 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "112",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 5,
        returnedCount: 5,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2336",
  },
  {
    fieldData: {
      ProductName: "Snow Prickly Pear",
      ProductType__c: "Potted Plants",
      Season: "",
      __kp_Product_ID: 10638,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 75.0,
          "prod_VARIANT::QtyOnHand": 91,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7638",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2337",
  },
  {
    fieldData: {
      ProductName: "Sol Garden Spa Box",
      ProductType__c: "Gift Boxes",
      Season: "",
      __kp_Product_ID: 10639,
      flag_topTen: "",
    },
    modId: "2",
    portalData: {
      prod_VARIANT: [
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 285.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7639",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2338",
  },
  {
    fieldData: {
      ProductName: "Sonoran Pin Cushion",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10640,
      flag_topTen: "",
    },
    modId: "3",
    portalData: {
      prod_VARIANT: [
        {
          modId: "8",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 150.0,
          "prod_VARIANT::QtyOnHand": 8,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7640",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Table Centerpieces",
          "prod_colljoin_COLL::Count": 32,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "81",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2339",
  },
  {
    fieldData: {
      ProductName: "Sunflower Mason Jar",
      ProductType__c: "Arrangement",
      Season: "",
      __kp_Product_ID: 10641,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "9",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Medium Mason",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 65.0,
          "prod_VARIANT::QtyOnHand": 9,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7641",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Summer 2025",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "80",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Flowers Under $100",
          "prod_colljoin_COLL::Count": 27,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "96",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2340",
  },
  {
    fieldData: {
      ProductName: "Teachers Cookie",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10642,
      flag_topTen: "",
    },
    modId: "4",
    portalData: {
      prod_VARIANT: [
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 14,
          "prod_VARIANT::SortOrder": 2,
          "prod_VARIANT::Unit": "",
          recordId: "7642",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 2,
        returnedCount: 2,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2341",
  },
  {
    fieldData: {
      ProductName: "Tony's Chocolate Dark Almond Sea Salt",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10643,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 27,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7643",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2342",
  },
  {
    fieldData: {
      ProductName: "Tony's Chocolate Everything Bar",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10644,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "0",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 21,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7644",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2343",
  },
  {
    fieldData: {
      ProductName: "Tony's Chocolate Milk Caramel Sea Salt",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10645,
      flag_topTen: "",
    },
    modId: "6",
    portalData: {
      prod_VARIANT: [
        {
          modId: "2",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 8.0,
          "prod_VARIANT::QtyOnHand": 2,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7645",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2344",
  },
  {
    fieldData: {
      ProductName: "Tony's Chocolate Rainbow Tester Pack",
      ProductType__c: "Edibles",
      Season: "",
      __kp_Product_ID: 10646,
      flag_topTen: "",
    },
    modId: "5",
    portalData: {
      prod_VARIANT: [
        {
          modId: "5",
          "prod_VARIANT::Category__lu": "",
          "prod_VARIANT::Description__c": "Default Title",
          "prod_VARIANT::Option2": "",
          "prod_VARIANT::Price": 18.0,
          "prod_VARIANT::QtyOnHand": 6,
          "prod_VARIANT::SortOrder": 1,
          "prod_VARIANT::Unit": "",
          recordId: "7646",
        },
      ],
      prod_colljoin_COLL: [
        {
          modId: "3",
          "prod_colljoin_COLL::Collection": "Back to School",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "74",
        },
        {
          modId: "6",
          "prod_colljoin_COLL::Collection": "Pantry",
          "prod_colljoin_COLL::Count": "",
          "prod_colljoin_COLL::isActive": 1,
          recordId: "76",
        },
        {
          modId: "2",
          "prod_colljoin_COLL::Collection": "Sweets",
          "prod_colljoin_COLL::Count": 50,
          "prod_colljoin_COLL::isActive": 1,
          recordId: "104",
        },
      ],
    },
    portalDataInfo: [
      {
        database: "Camelback",
        foundCount: 1,
        returnedCount: 1,
        table: "prod_VARIANT",
      },
      {
        database: "Camelback",
        foundCount: 3,
        returnedCount: 3,
        table: "prod_colljoin_COLL",
      },
    ],
    recordId: "2345",
  },
];